routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'ShopController@getProducts');

Route::post('select_ajax_items', ['as'=>'select_ajax_items','uses'=>'ShopController@ajaxFilter']);


Route::get('/admin', function () {
    return view('auth.login');
});

Auth::routes();


Route::get('/unverified', 'HomeController@unverified')->name('unverified');


Route::group(['middleware' => 'verified'], function () {



    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/restore_product/{id}', 'HomeController@restoreproduct');

    Route::resource('products', 'ProductController');
    Route::resource('brands', 'BrandController');
    Route::resource('processors', 'ProcessorController');
    Route::resource('screens', 'ScreenController');
    Route::resource('prices', 'PriceController');



});

resources/views/admin-includes/footer.blade.php
   <footer class="footer text-right">
       &copy; {{ date('Y')  }} {{ env('APP_NAME') }} All Rights Reserved
                </footer>

resources/views/admin-includes/head.blade.php
   <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{{ env('APP_NAME') }}">
        <meta name="author" content="{{ env('APP_NAME') }}">

        <link rel="shortcut icon" href="{{asset('assets/images/favicon.ico')}}">

        <title>{{ env('APP_NAME') }}</title>

        <!--Morris Chart CSS -->
		<link rel="stylesheet" href="{{asset('assets/plugins/morris/morris.css')}}">

        <!-- App css -->
        <link href="{{asset('assets/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{asset('assets/css/icons.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{asset('assets/css/style.css')}}" rel="stylesheet" type="text/css" />

        <script src="{{asset('assets/js/modernizr.min.js')}}"></script>

    </head>

resources/views/admin-includes/home-inner-content.blade.php
            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container-fluid">

                       <div class="row">
                            <div class="col-xl-4 col-sm-6 col-6">
                                <div class="card-box widget-user">
                                    <div class="text-center">
                                        <h2 class="text-custom" data-plugin="counterup">{{ $brands }}</h2>
                                        <h5>Brands</h5>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xl-4 col-sm-6 col-6">
                                <div class="card-box widget-user">
                                    <div class="text-center">
                                        <h2 class="text-pink" data-plugin="counterup">{{ $processors }}</h2>
                                        <h5>Processors</h5>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xl-4 col-sm-6 col-6">
                                <div class="card-box widget-user">
                                    <div class="text-center">
                                        <h2 class="text-info" data-plugin="counterup">{{ $products }}</h2>
                                        <h5>Products</h5>
                                    </div>
                                </div>
                            </div>


                        </div>


                    </div> <!-- container -->

                </div> <!-- content -->

                 </div>

resources/views/admin-includes/left-side-bar.blade.php
      <div class="left side-menu">
                <div class="sidebar-inner slimscrollleft">

                    <!-- User -->
                    <div class="user-box">
                        <div class="user-img">
                            <img src="{{asset('assets/images/users/avatar-1.jpg')}}" alt="user-img" title="{{ Auth::user()->name }}" class="rounded-circle img-thumbnail img-responsive">
                            <div class="user-status offline"><i class="mdi mdi-adjust"></i></div>
                        </div>

                        <h5><a href="#">{{ Auth::user()->name }}</a> </h5>
                        <ul class="list-inline">
                            <li class="list-inline-item">
                                <a href="" >
                                    <i class="mdi mdi-settings"></i>
                                </a>
                            </li>

                            <li class="list-inline-item">
                               <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"class="text-custom">
                                    <i class="mdi mdi-power"></i>
                                </a>
                                 <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                            </li>
                        </ul>
                    </div>
                    <!-- End User -->

                    <!--- Sidemenu -->
                    <div id="sidebar-menu">
                        <ul>

                            <li>
                                <a href="{{ route('home') }}" class="waves-effect"><i class="mdi mdi-home"></i> <span> Home </span> </a>
                            </li>

                            <li>
                                <a href="{{ route('brands.index') }}" class="waves-effect"><i class="mdi mdi-star-circle"></i> <span> Brands </span> </a>
                            </li>
                            <li>
                                <a href="{{ route('processors.index') }}" class="waves-effect"><i class="mdi mdi-star-circle"></i> <span> Processors </span> </a>
                            </li>
                            <li>
                                <a href="{{ route('products.index') }}" class="waves-effect"><i class="mdi mdi-star-circle"></i> <span> Products </span> </a>
                            </li>
                            <li>
                                <a href="{{ route('screens.index') }}" class="waves-effect"><i class="mdi mdi-star-circle"></i> <span> Screen Size </span> </a>
                            </li>
                            <li>
                                <a href="{{ route('prices.index') }}" class="waves-effect"><i class="mdi mdi-star-circle"></i> <span> Price Range </span> </a>
                            </li>




                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <!-- Sidebar -->
                    <div class="clearfix"></div>

                </div>

            </div>

resources/views/admin-includes/right-side-bar.blade.php
            <!-- Right Sidebar -->
            <div class="side-bar right-bar">
                <a href="javascript:void(0);" class="right-bar-toggle">
                    <i class="mdi mdi-close-circle-outline"></i>
                </a>
                <h4 class="">Notifications</h4>
                <div class="notification-list nicescroll">
                    <ul class="list-group list-no-border user-list">
                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="avatar">
                                    <img src="{{asset('assets/images/users/avatar-2.jpg')}}" alt="">
                                </div>
                                <div class="user-desc">
                                    <span class="name">Michael Zenaty</span>
                                    <span class="desc">There are new settings available</span>
                                    <span class="time">2 hours ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="icon bg-info">
                                    <i class="mdi mdi-account"></i>
                                </div>
                                <div class="user-desc">
                                    <span class="name">New Signup</span>
                                    <span class="desc">There are new settings available</span>
                                    <span class="time">5 hours ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="list-group-item">
                            <a href="#" class="user-list-item">
                                <div class="icon bg-pink">
                                    <i class="mdi mdi-comment"></i>
                                </div>
                                <div class="user-desc">
                                    <span class="name">New Message received</span>
                                    <span class="desc">There are new settings available</span>
                                    <span class="time">1 day ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="list-group-item active">
                            <a href="#" class="user-list-item">
                                <div class="avatar">
                                    <img src="{{asset('assets/images/users/avatar-3.jpg')}}" alt="">
                                </div>
                                <div class="user-desc">
                                    <span class="name">James Anderson</span>
                                    <span class="desc">There are new settings available</span>
                                    <span class="time">2 days ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="list-group-item active">
                            <a href="#" class="user-list-item">
                                <div class="icon bg-warning">
                                    <i class="mdi mdi-settings"></i>
                                </div>
                                <div class="user-desc">
                                    <span class="name">Settings</span>
                                    <span class="desc">There are new settings available</span>
                                    <span class="time">1 day ago</span>
                                </div>
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
            <!-- /Right-bar -->

resources/views/admin-includes/top-bar.blade.php
 <div class="topbar">

                <!-- LOGO -->
                <div class="topbar-left">
                    <a href="{{ route('home') }}" class="logo"><span>{{ env('APP_NAME') }}<span>{{ env('APP_NAME_SUB') }}</span></span><i class="mdi mdi-layers"></i></a>
                </div>

                <!-- Button mobile view to collapse sidebar menu -->
                <div class="navbar navbar-default" role="navigation">
                    <div class="container-fluid">


 <!-- Page title -->
                        <ul class="nav navbar-nav list-inline navbar-left">
                            <li class="list-inline-item">
                                <button class="button-menu-mobile open-left">
                                    <i class="mdi mdi-menu"></i>
                                </button>
                            </li>
                            <li class="list-inline-item">
                                <h4 class="page-title"> @yield('title')</h4>
                            </li>
                        </ul>




                    </div><!-- end container -->
                </div><!-- end navbar -->
            </div>